### PR TITLE
add lucasC view and e2e test

### PR DESCRIPTION
**Pull request by Redeltaz**

### CODE REVIEW

**Comment by Antogin** [comment]
Hello hello,
It's a missing a link in the header:
Screenshot 2021-09-22 at 15 13 22

**Comment by Redeltaz** [comment]
> Hello hello,
> It's a missing a link in the header:
> Screenshot 2021-09-22 at 15 13 22

fixed :)

**Comment by Antogin** [comment]
/Users/georgesantonioindrianjafy/dev/lucasC/src/App.vue
  8:1  warning  Delete `⏎`  prettier/prettier

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.

**Comment by Redeltaz** [comment]
> /Users/georgesantonioindrianjafy/dev/lucasC/src/App.vue
> 8:1 warning Delete `⏎` prettier/prettier
> 
>  1 problem (0 errors, 1 warning)
> 0 errors and 1 warning potentially fixable with the `--fix` option.

Refixed

**Pull request merged**
